#!/usr/bin/env zsh

# Navigation
alias cp='cp -i'
alias mv='mv -i'

# alias -='\cd -' # Efforts to correct this have failed
alias dot="\cd ~/dotfiles"
alias cddot="\cd ~/dotfiles"
alias ..='\cd ..; l'
alias ...='\cd ../..; l'
alias ....='\cd ../../..; l'
alias pud='\pushd'
alias pod='\popd'

# ls behaves strangely on newer versions of macOS
# override the default ls with gls
local LIST_METHOD="ls"
if expr "$OSTYPE" : 'darwin' >/dev/null; then
  LIST_METHOD="gls"
fi

alias l="$LIST_METHOD --group-directories-first --color=tty"
alias ll="$LIST_METHOD -lAh --group-directories-first --color=tty"
alias la="$LIST_METHOD -A --group-directories-first --color=tty"

# ls after cd
function c() {
  \cd "$1"; l  || exit
}

# mkdir and change to it
function mcd () {
  mkdir -p "$1"
  cd "$1" || exit
}

# FZF
alias a=search_and_print_alias

# PROGRAMS
alias v="$EDITOR"
alias python=python3
alias tree="tree -I 'node_modules|submodules|backup-dotfiles'"
alias ghce="gh copilot explain"
alias ghcs="gh copilot suggest"

# SEARCH TOOL
local excluded_dirs=(
  "submodules"
  "backup-dotfiles"
  ".git"
  "node_modules"
  "__pycache__"
)
local excluded_files=(
  "Brewfile.lock.json"
)

local SEARCH_COMMAND=""
if type -p rg >/dev/null 2>&1; then
    SEARCH_COMMAND="rg --no-ignore"
    for dir in "${excluded_dirs[@]}"; do
        SEARCH_COMMAND+=" --glob '!$dir/'"
    done
    for file in "${excluded_files[@]}"; do
        SEARCH_COMMAND+=" --glob '!$file'"
    done
else
  SEARCH_COMMAND="grep -r"
  for dir in "${excluded_dirs[@]}"; do
      SEARCH_COMMAND+=" --exclude-dir=$dir"
  done
  for file in "${excluded_files[@]}"; do
      SEARCH_COMMAND+=" --exclude=$file"
  done
fi

alias -g g="| $SEARCH_COMMAND"
alias -g gi="| $SEARCH_COMMAND -i"
alias -g gv="| $SEARCH_COMMAND -v"
alias rg="$SEARCH_COMMAND"

# MISC
alias cl="clear"
