#!/usr/bin/env zsh
# git aliases

alias rpull="pull --rebase"
alias gcob="git checkout -b"
alias gcop="git checkout -p"
alias gcfix="git commit --fixup"
alias gmv="git mv"
alias grbo='git rebase origin/"$(git_current_branch)"'
alias grbmi='git rebase -i $(git_main_branch)'
alias grbim='git rebase -i $(git_main_branch)'
alias gbm='git branch --move'
alias gdm='git diff "$(git_main_branch)"'
alias gstam="git stash push -m"
alias gstap="git stash push -p"
alias grevc="git revert --continue"
alias greva="git revert --abort"
alias vgdm='vim_git_diff $(git merge-base "$(git_current_branch)" "$(git_main_branch)")'
alias vgd=vim_git_diff
alias vcd=vim_commit_diff

function vim_git_diff() {
  nvim $(gd --name-only $1 | xargs)
}

function vim_commit_diff() {
  nvim $(git diff-tree --no-commit-id --name-only -r $1 | xargs)
}

# remove oh my zsh git pull aliases
unalias gl
unalias ggpull
unalias glum
unalias gpoat
unalias grhh
