#!/usr/bin/env bash
#
# ALIASES
alias lA="ls -A"
alias -g g="| grep"
alias -g gi="| grep -i"
alias cddot="cd ~/dotfiles"
alias cl="clear"

# FUNCTIONS
# ls after cd
function cs() {
  cd "$1" || exit
  ls
}

# mkdir and change to it
function mcd () {
  mkdir -p "$1"
  cd "$1" || exit
}
