#!/usr/bin/env zsh

# OVERWRITE ALIASES
alias cp='cp -i'
alias mv='mv -i'

# ALIASES
# ls behaves strangely on newer versions of macOS
if [ "$OSTYPE" = 'linux-gnu' ]; then
    alias l="\ls --group-directories-first --color=tty"
    alias ll="\ls -lAh --group-directories-first --color=tty"
    alias la="\ls -A --group-directories-first --color=tty"
else
    alias l="\gls --group-directories-first --color=tty"
    alias ll="\gls -lAh --group-directories-first --color=tty"
    alias la="\gls -A --group-directories-first --color=tty"
fi

alias ls="echo use l"
alias -g g="| grep"
alias -g gi="| grep -i"
alias cd="echo use c"
alias cddot="\cd ~/dotfiles"
alias cl="clear"
alias ..='\cd ..; \ls'
alias ...='\cd ...; \ls'
alias ....='\cd ....; \ls'
alias pud='\pushd'
alias pod='\popd'

# Programs
alias v="\nvim"
alias vim="echo use v"

# FUNCTIONS
# ls after cd
function c() {
  \cd "$1" || exit
  l
}

# mkdir and change to it
function mcd () {
  mkdir -p "$1"
  cd "$1" || exit
}
