#!/usr/bin/env zsh

# OVERWRITE ALIASES
alias cp='cp -i'
alias mv='mv -i'

# ALIASES
# ls behaves strangely on newer versions of macOS
if [ "$OSTYPE"==linux-gnu ]; then  # Is this the Ubuntu system?
    alias ll='ls -Flh --group-directories-first'
else
    alias ll='gls -Flh --group-directories-first'
fi
alias lA="ls -A"
alias -g g="| grep"
alias -g gi="| grep -i"
alias cddot="cd ~/dotfiles"
alias cl="clear"
alias ..='cd ..; ls'
alias ...='cd ...; ls'
alias ....='cd ....; ls'
alias pud='pushd'
alias pod='popd'

# FUNCTIONS
# ls after cd
function cs() {
  cd "$1" || exit
  ls
}

# mkdir and change to it
function mcd () {
  mkdir -p "$1"
  cd "$1" || exit
}
