#!/usr/bin/env zsh

# Oh My Zsh
export ZSH="$HOME"/.oh-my-zsh

ZSH_THEME="robbyrussell"

# Plugins
plugins=(
  git
  fasd
)
source "$ZSH"/oh-my-zsh.sh


# SETTINGS
export EDITOR="vim"
unsetopt BEEP                   # Turn off all beeps
setopt interactive_comments     # Allow interactive comments
setopt noclobber                # Don't overwrite files by default when using '>'
setopt autopushd                # cd acts like pushd
setopt autocd
HYPHEN_INSENSITIVE=true
COMPLETION_WAITING_DOTS=true
HIST_STAMPS='yyyy-mm-dd'        # Show history time stamp

# aliases
for file in $(\ls -A "$HOME"/dotfiles/aliases | grep -E '[^s][^w].$'); do
    source "$HOME"/dotfiles/aliases/"$file"
done
unset file

# functions
for file in $(\ls -A "$HOME"/dotfiles/functions | grep '[^s][^w].$') ; do
    source "$HOME"/dotfiles/functions/"$file"
done
unset file

# zsh
if [[ -f "$HOME"/dotfiles/zsh/zshrc.local ]]; then
  source "$HOME"/dotfiles/zsh/zshrc.local
fi

# FZF
if command -v bat &> /dev/null
then
  export FZF_DEFAULT_OPTS="--preview 'bat --style=numbers --color=always --line-range :500 {}'"
else
  export FZF_DEFAULT_OPTS="--preview 'cat {}'"
  echo "********************************************************************************\n"
  echo "Install bat!"
  echo "********************************************************************************\n"
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# git config
if [[ -f "$HOME"/dotfiles/git-config.sh ]]; then
  source "$HOME"/dotfiles/git-config.sh
fi

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# Set PATH, MANPATH, etc., for Homebrew.
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
