#!/usr/bin/env zsh

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Path to your oh-my-zsh installation.
 export ZSH="$HOME"/.oh-my-zsh

# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
# ZSH_THEME="robbyrussell"

HYPHEN_INSENSITIVE=true

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Show history  time stamp
HIST_STAMPS="yyyy-mm-dd"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(
  git
)

source "$ZSH"/oh-my-zsh.sh

export EDITOR="vim"

# Turn off all beeps
unsetopt BEEP

# aliases
# WARNING: currently file is becoming a global variable. I don't know how to stop that
# TODO
for file in $(ls -A "$HOME"/dotfiles/aliases | grep -E '[^s][^w].$'); do
    source "$HOME"/dotfiles/aliases/"$file"
done

# functions
for file in $(ls -A "$HOME"/dotfiles/functions | grep '[^s][^w].$') ; do
    source "$HOME"/dotfiles/functions/"$file"
done
unset file

# zsh
if [[ -f "$HOME"/dotfiles/zsh/zshrc.local ]]; then
  source "$HOME"/dotfiles/zsh/zshrc.local
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# git config
if [[ -f "$HOME"/dotfiles/git-config.sh ]]; then
  source "$HOME"/dotfiles/git-config.sh
fi

source "$HOME"/dotfiles/zsh/themes/powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
