#!/usr/bin/env zsh

# Set PATH, MANPATH, etc., for Homebrew.
if [ "$OSTYPE" = 'linux-gnu' ]
then
  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fi
# OH MY ZSH
export ZSH="$HOME"/.oh-my-zsh
export ZSH_COMPDUMP=$ZSH/cache/completions/.zcompdump-$HOST
# omz settings
ZSH_THEME="robbyrussell"
# ZSH_THEME_RANDOM_CANDIDATES=(
#   agnoster
#   robbyrussell
# )
ZSH_DISABLE_COMPFIX=true
COMPLETION_WAITING_DOTS=true
HYPHEN_INSENSITIVE=true
HIST_STAMPS="yyyy-mm-dd"

# PLUGINS
plugins=(
  git
  zsh-autosuggestions
  zsh-syntax-highlighting
  fasd
)
source "$ZSH"/oh-my-zsh.sh


# SETTINGS
export EDITOR="vim"
unsetopt BEEP                   # Turn off all beeps
setopt interactive_comments     # Allow interactive comments
setopt noclobber                # Don't overwrite files by default when using '>'
setopt autopushd                # cd acts like pushd
setopt autocd
HYPHEN_INSENSITIVE=true
COMPLETION_WAITING_DOTS=true
# Prevent CTRL+D from logging out immediately
# Waits 1 second for the second CTRL+D
# If you want to log out immediately, just press CTRL+D twice
export IGNOREEOF=1

# COLORS
export LESS_TERMCAP_mb=$'\e[1;32m'
export LESS_TERMCAP_md=$'\e[1;32m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[01;33m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[1;4;31m'

# HISTORY OPTIONS
setopt EXTENDED_HISTORY            # Record timestamp
HIST_STAMPS='yyyy-mm-dd'           # Show history time stamp
export HISTTIMEFORMAT="[%F %T] "   # Timestamp format
export HISTFILESIZE=1000000        # Max history file size
export HISTSIZE=1000000            # Max history to load in memory
setopt INC_APPEND_HISTORY          # Save to history immediately
setopt HIST_FIND_NO_DUPS           # Only show commands once when searching with CTRL+R


# SOURCE SECRETS
[ -f "$HOME/.secrets" ] && source "$HOME/.secrets"

# SOURCE ALIASES
for file in $(\ls -A "$HOME"/dotfiles/aliases | grep -E '[^s][^w].$'); do
    source "$HOME"/dotfiles/aliases/"$file"
done
unset file

# SOURCE FUNCTIONS
for file in $(\ls -A "$HOME"/dotfiles/functions | grep '[^s][^w].$') ; do
    source "$HOME"/dotfiles/functions/"$file"
done
unset file

# LOCAL SETINGS
if [[ -f "$HOME"/dotfiles/zsh/zshrc.local ]]; then
  source "$HOME"/dotfiles/zsh/zshrc.local
fi

# BAT
if command -v bat &> /dev/null
then
  export FZF_DEFAULT_OPTS="--preview 'bat --style=numbers --color=always --line-range :500 {}'"
else
  export FZF_DEFAULT_OPTS="--preview '\cat {}'"
  echo "********************************************************************************\n"
  echo "Install bat!"
  echo "********************************************************************************\n"
fi

# FZF
if command -v fzf &> /dev/null
then
  [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
  # use rg
  # exclude .git, node_modules, and submodules
  export FZF_DEFAULT_COMMAND='rg --files --hidden --follow --glob "!{.git,node_modules,~/dotfiles/submodules}/*"'
  export FZF_CTRL_T_COMMAND=$FZF_DEFAULT_COMMAND
else
  echo "********************************************************************************\n"
  echo "Install fzf!"
  echo "********************************************************************************\n"
fi

# GIT CONFIG
if [[ -f "$HOME"/dotfiles/git-config.sh ]]; then
  source "$HOME"/dotfiles/git-config.sh
fi

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

source /home/matt/.config/broot/launcher/bash/br
